import sqlite3

DESCRIPTIONS = {
    "Kaleiçi (Eski Şehir)": "Antalya'nın kalbi olan Kaleiçi, 2.000 yıllık tarihin yaşayan tanığıdır. Roma surları, Osmanlı konakları ve Bizans kiliseleri aynı dar sokaklarda bir arada bulunur. Gün batımında sur üzerinde yürüyerek manzarayı seyretmek, ziyaretin en unutulmaz anlarından biridir.",
    "Hadrian Kapısı": "MS 130 yılında Roma İmparatoru Hadrian'ın Antalya'yı ziyaretini onurlandırmak için inşa edilen bu üç kemerli mermer kapı, Kaleiçi'nin simgesi hâline gelmiştir. 12 metre yüksekliğindeki beyaz mermer kemerleri ve Roma dönemine ait kabartmalarıyla görkemli bir giriş noktasıdır. Antik çağdan bu yana büyük ölçüde özgün hâlini koruması bakımından son derece nadir bir yapıdır.",
    "Yivli Minare": "13. yüzyılda Anadolu Selçukluları tarafından inşa edilen Yivli Minare, Antalya'nın en tanınmış siluetini oluşturur. Sekiz dilimli gövdesi ve lacivert sırlı tuğla kaplamasıyla Türk-İslam mimarisinin özgün bir örneğidir. Kaleiçi'nde camiyle birlikte günümüzde de ayakta duran yapı, şehrin en çok fotoğraflanan noktalarından biridir.",
    "Saat Kulesi": "19. yüzyıl sonunda inşa edilen Saat Kulesi, eski çarşı ile Kaleiçi'nin kesiştiği noktada yer almaktadır. Osmanlı dönemi sivil mimarisinin tipik özelliklerini yansıtan kule, tarihi Kalekapı meydanının odak noktasıdır. Çevresindeki kahvehaneler ve sokak dokusuyla birlikte geleneksel Antalya atmosferini günümüze taşır.",
    "Hıdırlık Kulesi": "MS 2. yüzyılda Roma döneminde inşa edilen Hıdırlık Kulesi, yüzyıllar içinde gözetleme kulesi ve deniz feneri olarak kullanılmıştır. Sahil kıyısındaki parkta yer alan kule, denize ve eski limana bakan panoramik konumuyla özellikle gün batımında büyüleyici bir manzara sunar. Kaleiçi'nin güney ucunda, sahil yürüyüş yolunun üzerinde bulunmaktadır.",
    "Perge Antik Kenti": "MÖ 3. yüzyılda kurulan Perge, Pamfilya bölgesinin en önemli antik kentlerinden biridir. Helenistik kapısı, Romalılar dönemine ait kolonlu caddesi ve stadyumunun yanı sıra büyük bir tiyatro ile hamamları barındırır. Yürüyüş güzergâhları arasında en zengin arkeolojik deneyimi sunan kentlerden biridir; kazılardan çıkan eserler Antalya Müzesi'nde sergilenmektedir.",
    "Aspendos Tiyatrosu": "MS 2. yüzyılda inşa edilen Aspendos Tiyatrosu, dünyanın en iyi korunmuş Roma tiyatrolarından biridir. 15.000 seyirci kapasitesiyle o dönemde bölgenin en büyük eğlence mekânlarından biri olmuştur. Sahne binasının tamamen ayakta olması ve akustiğin hâlâ olağanüstü işlemesi nedeniyle günümüzde opera ve konser mekânı olarak da kullanılmaktadır.",
    "Termessos Antik Kenti": "Torosların 1.050 metre yüksekliğindeki zirvelerinde kurulu Termessos, Büyük İskender'in dahi almaktan vazgeçtiği efsanevi kenttir. Millî park içindeki kalıntılar arasında tiyatro, agora, nekropol ve büyük sarnıçlar bulunmaktadır. Çevresindeki çam ormanları ve dağ manzarası, arkeolojik geziye olağanüstü bir doğa yürüyüşü deneyimi ekler.",
    "Phaselis Antik Kenti": "Üç körfezi olan Phaselis, yat turları ve kara ulaşımıyla kolayca ulaşılabilen nadir antik kentlerden biridir. Korunaklı plajları, kolonlu ana caddesi ve antik limanın izlerini taşıyan su kıyısı kalıntıları aynı anda keşfedilebilir. Çam ormanlarıyla çevrili bu konumu, yıllık milyonlarca ziyaretçiyi çeken popüler bir kültürel ve doğa turizmi noktası hâline getirmiştir.",
    "Olympos Antik Kenti": "Olympos, Likya'nın gizemli antik kentlerinden biri olarak Antalya'nın güneybatısında uzanan sahil ormanlarına gömülüdür. Kalıntılar arasında Hadrian tapınağı, nekropol ve antik liman yer almakta; kentin kıyı kesiminde ise masmavi bir plaj uzanmaktadır. Birkaç kilometre uzaktaki Yanartaş'ın milattan önce yanan alevleri, antik çağda bu bölgeye efsanevi bir hava katmıştır.",
    "Antalya Müzesi": "Türkiye'nin en zengin arkeoloji müzelerinden biri olan Antalya Müzesi, bölgedeki antik kentlerden çıkarılan on binlerce eseri barındırmaktadır. Perge başta olmak üzere Aspendos ve Side'den getirilen heykeller, altın takılar ve mozaikler dünyanın dört bir yanından müze ziyaretçisini çekmektedir. Tarih öncesi dönemden Bizans çağına uzanan geniş koleksiyonuyla bir günde tüm Anadolu medeniyetlerini izlemek mümkündür.",
    "Kaleiçi Müzesi": "Restore edilmiş tarihi bir Osmanlı konutunda yer alan Kaleiçi Müzesi, şehrin tarihini yöresel eserler ve fotoğraflarla aktarmaktadır. Küçük ama derli toplu koleksiyonu sayesinde Antalya'nın yakın geçmişini, el sanatlarını ve gündelik hayatını anlamak için ideal bir başlangıç noktasıdır. Kaleiçi'nin kıvrımlı sokakları arasındaki konumu ziyareti daha keyifli bir keşfe dönüştürür.",
    "Suna & İnan Kıraç Müzesi": "Kaleiçi'nin tarihi bir konağında kurulan Suna ve İnan Kıraç Müzesi, Osmanlı dönemi etnografya eserlerini ve geleneksel yaşam sahnelerini sergiler. Özenle restore edilmiş mekânı ve bahçesiyle şehrin en görkemli özel müzelerinden biri kabul edilir. Seramik koleksiyonu ve dönemine ait gündelik nesnelerle Anadolu'nun kültürel belleğini gün yüzüne çıkarır.",
    "Antalya Akvaryumu": "Konyaaltı sahilinde yer alan Antalya Akvaryumu, dünyanın en uzun tünel akvaryumlarından birini bünyesinde barındırır. 40 metrelik cam tünelden geçerken köpekbalığı, vatoz ve renkli tropikal balıkları yakın mesafeden izlemek mümkündür. Aile dostu temalı bölümleri, sanal gerçeklik deneyimleri ve yaşayan yağmur ormanı kubbesiyle hem çocuklara hem yetişkinlere hitap eder.",
    "Land of Legends": "Land of Legends, Belek'te konumlanan Türkiye'nin en büyük tatil ve eğlence parklarından biridir. Dev su kaydırakları, dalga havuzu ve adrenalin dolu binicilik parkurlarının yanı sıra otel, alışveriş merkezi ve restoran gibi imkânları tek çatı altında sunar. Tüm gün sürecek ailece eğlence arayanlar için ideal bir destinasyondur.",
    "Antalya Hayvanat Bahçesi": "Antalya Hayvanat Bahçesi, şehir merkezine yakın yeşil bir alanda 200'den fazla hayvan türüne ev sahipliği yapar. Aslan, kaplan ve zürafanın yanı sıra çeşitli sürüngen ve kuş türlerini barındıran park, çocuklu aileler için popüler bir gezi noktasıdır. Geniş yeşil alanları ve piknik köşeleriyle şehrin içinde huzurlu bir gün geçirmek için uygundur.",
    "Konyaaltı Plajı": "Antalya'nın en uzun şehir plajı olan Konyaaltı, 7 kilometre boyunca Beydağları manzarasıyla uzanır. Çakıl ve kum karışımı kıyısında yüzme, sörf ve paddleboard gibi su sporlarının yanı sıra sahil şeridindeki kafeler ve rekreasyon alanlarından yararlanmak mümkündür. Gün batımında dağların siletiyle birleşen deniz manzarası, Antalya'nın en ikonik kartpostal görüntülerinden birini oluşturur.",
    "Lara Plajı": "Antalya'nın doğusunda uzanan Lara Plajı, şehrin en uzun kum kıyısıdır ve uluslararası düzeyde tanınan lüks tatil köyleriyle çevrilidir. Sakin ve berrak suları ile plaj sporları için elverişli yapısı sayesinde hem yerli hem yabancı turistlerin gözdesidir. Kıyı boyunca sıralanan restoranlar; Rus mutfağından yerel Türk lezzetlerine kadar geniş bir seçenek sunar.",
    "Mermerli Plajı": "Kaleiçi surlarının hemen dibinde, kayalık bir girinti üzerine kurulu Mermerli, şehrin en küçük ve en atmosferik plajlarından biridir. Tarihi dokuyla denizin iç içe geçtiği bu nadir köşe özellikle erken saatlerde huzurlu bir yüzme deneyimi sunar. Plaj restoranında tarihi sur manzarası eşliğinde yenilen kahvaltı, bir Antalya ritüeline dönüşmüştür.",
    "Kaputaş Plajı": "Antalya ile Kaş arasındaki kıyı yolunda iki sarp kayalık arasına sıkışmış Kaputaş, Türkiye'nin en fotoğraflanan doğal mekânlarından biridir. Turkuaz rengindeki derin suyu ve beyaz çakıllı kıyısıyla gün boyu güneşlenme ve yüzme imkânı sunar. Denize inen 187 basamaklı merdiven erişimi kısıtladığı için kalabalıktan uzak bir deneyim arayanlar için idealdir.",
    "Çıralı Plajı": "Olympos'un hemen kuzeyinde çam ve portakal bahçelerinin arasında saklı Çıralı, Caretta caretta kaplumbağalarının yumurtlama alanı olduğundan koruma bölgesindedir. Yaklaşık 3 kilometre uzunluğundaki kumlu plajı sakin ve bakir yapısını korumaktadır; kamp ve küçük apart tesisler dışında büyük otel yoktur. Geceleri kaplumbağa yuvaları için belirlenmiş bölgelerde kaplumbağa gözlemi yapılabilmektedir.",
    "Club Arma Beach": "Kaleiçi sahil surlarının dibinde, tarihi doku içinde konumlanan Club Arma Beach, Antalya'nın en prestijli plaj kulüplerinden biridir. Özel şezlong ve şemsiyeleri, havuzu ve tam donanımlı restoranıyla açık deniz yerine kayalık kıyıda yüzme imkânı sunar. Akşam saatlerinde mekân bir deniz kenarı restoranı ve bar olarak faaliyetini sürdürür.",
    "Konyaaltı Beach Park": "Konyaaltı Sahil Parkı'nın içinde yer alan Beach Park, halkın ücretsiz olarak yararlanabileceği geniş plaj alanları ve kafe bölümleri sunar. Uzun rıhtımı, voleybol sahası ve bisiklet yollarıyla şehrin en kapsamlı sahil rekreasyon tesisidir. Ailelere ve spor tutkunlarına hitap eden düzenlenmesiyle özellikle hafta sonları Antalyalıların yoğun ilgisini çeker.",
    "Lara Beach Club": "Lara Plajı'nın hemen kıyısında konumlanan Lara Beach Club, yetişkinlere yönelik lüks bir plaj ve havuz deneyimi sunmaktadır. Şezlong kiralama, özel servis ve canlı müzik etkinlikleriyle tam anlamıyla premium bir gün geçirme mekânıdır. Akşam saatlerinde bar ve disko olarak dönüşen mekân, Lara'nın gece hayatının da merkezine oturmaktadır.",
    "Düden Şelalesi (Alt)": "Düden Çayı'nın denize döküldüğü noktada oluşan Alt Düden Şelalesi, Türkiye'de denize dökülen ender şelalelerden biridir. Kayalık falezden yaklaşık 40 metre aşağıya düşen şelale, tekneden izlendiğinde en etkileyici görünümünü kazanır; Kaleiçi Limanı'ndan kalkan tekneler bu noktaya uğrar. Yanındaki sahil yürüyüş yolundan da şelale seyredilir.",
    "Düden Şelalesi (Üst)": "Üst Düden Şelalesi, şehrin kuzeyindeki yeşil bir parkın içinde doğal bir kanyon oluşturarak akar. Mağara arkasından geçerek şelalenin önüne ulaşılan yürüyüş güzergâhı özellikle çocuklu aileler için heyecanlı bir macera sunar. Park içindeki piknik alanları ve yürüyüş yollarıyla birlikte yarım günlük keyifli bir gezi planlanabilir.",
    "Kurşunlu Şelalesi": "Antalya'ya yaklaşık 19 kilometre uzaklıktaki çam ormanlarının içine gizlenmiş Kurşunlu Şelalesi, kaskat basamaklar hâlinde dökülen suyu ve etrafındaki yoğun yeşilliğiyle fotoğraf tutkunlarının gözdesidir. Millî park sınırları içindeki yürüyüş rotaları, sabah erken saatlerinde buharla kaplı şelaleye ulaşmak için benzersiz bir deneyim sunar. Piknik masaları ve yürüyüş yollarıyla sakin bir doğa günü planlanabilir.",
    "Manavgat Şelalesi": "Manavgat Nehri'nin geniş yatak üzerinde döküldüğü Manavgat Şelalesi, yüksek değil ama olağanüstü geniş bir su kütlesiyle büyüleyicidir. Şelale kenarındaki restoran ve kahvehanelerde nehir manzarasına karşı yöresel lezzetleri tatmak ziyaretin en keyifli bölümünü oluşturur. Yakınındaki Side Antik Kenti ile birleştirilerek günübirlik bir gezi planlanması tavsiye edilir.",
    "Konyaaltı Sahil Parkı": "Konyaaltı Plajı boyunca uzanan Sahil Parkı, bisiklet yolları, egzersiz alanları, açık hava kafeler ve çocuk oyun alanlarıyla şehrin en büyük rekreasyon koridorudur. Sabah yürüyüşlerinden gün batımı pikniklerine kadar her saatte dolup taşan park, yerel halkın şehir yaşantısına katılma biçimini yansıtır. Denize bakan kafelerde oturarak Beydağları manzarasını izlemek başlı başına bir deneyimdir.",
    "Atatürk Parkı": "Şehir merkezinde konumlanan Atatürk Parkı, gölgeli çınar ağaçları ve serin çeşmeleriyle günlük yaşamın yavaşladığı bir nefes alma noktasıdır. Sabah kahvesini şehrin gürültüsünden uzakta içmek isteyenler için ideal olan park; hafta sonları pazar, konser ve festival etkinliklerine de ev sahipliği yapar. Yakınındaki tarihi çarşı ile birleştirildiğinde Antalya'nın sosyal dokusunu hissettirir.",
    "Düden Parkı": "Üst Düden Şelalesi'nin çevresinde kurulu Düden Parkı, doğal kanyon manzarası ve yoğun çam ormanıyla şehre yakın doğa yürüyüşlerinin en popüler adreslerinden biridir. Şelalenin gerisindeki mağaranın içinden geçerek suyun arkasından izlenebildiği bir yürüyüş güzergâhı mevcuttur. Piknik masaları ve açık hava oturma alanlarıyla ailelere tam anlamıyla bir doğa günü yaşatır.",
    "Köprülü Kanyon Milli Parkı": "Toros Dağları'nın derinliklerine kazınmış Köprülü Kanyon, Antalya'ya 97 kilometre uzaklıkta yer almakta ve rafting ile kanyoning sporlarının Türkiye'deki en gözde noktalarından birini oluşturmaktadır. Nehir üzerindeki iki Roma köprüsü hâlâ ayakta ve kullanılabilir durumdadır. Kanyon içindeki alabalık restoranları, rafting heyecanının ardından dinlenme fırsatı sunar.",
    "Dim Mağarası": "Alanya'ya 11 kilometre uzaklıktaki Dim Çayı vadisinde yer alan Dim Mağarası, 360 metre uzunluğundaki sarkıt ve dikitlileriyle görsel bir şölen sunar. Mağaranın sonunda bulunan küçük göl, aynadan yansır gibi mağara tavanının yansımasını sunar. Alanya gezisiyle kolaylıkla birleştirilebilecek yarım günlük doğa ve kültür turu için ideal bir duraktır.",
    "Karain Mağarası": "Antalya'ya 27 kilometre uzaklıkta bulunan Karain Mağarası, Türkiye'nin bilinen en büyük prehistorik yerleşim alanıdır; burada 400.000 yıl önceye uzanan insan kalıntıları bulunmuştur. UNESCO Dünya Mirası Geçici Listesi'nde yer alan mağarada Paleolitik, Neolitik ve Kalkolitik dönemlere ait çeşitli aletler ele geçirilmiştir. Mağara girişindeki küçük sergi alanı, kazılardan elde edilen buluntular hakkında bilgilendirici içerik sunar.",
    "Altınbeşik Mağarası": "Manavgat yakınlarında yer alan Altınbeşik Mağarası, Türkiye'nin sayılı yeraltı gölü mağaralarından biridir. Ziyaretçiler ahşap platformlar üzerinde yürüyerek ve sandal ile giderek mağaranın derinliklerine ulaşabilir; içerideki göl tekne turu imkânı sunmaktadır. Müzekart ile ücretsiz ziyaret edilebilen mağara, Köprülü Kanyon gezisiyle aynı güne sığdırılabilir.",
    "Kaleiçi Bazaar": "Kaleiçi'nin tarihi surları içindeki Uzun Çarşı ve çevre sokaklarda uzanan Kaleiçi Bazaar, yüzyıllardır esnafın soluğunu kesen ticaret merkezidir. El dokuması halılar, bakır işlemeli çaydanlıklar, lüfer boncuklu takılar ve baharatlar dolu bu çarşıda pazarlık kültürünü yaşamak ziyaretin ayrılmaz bir parçasıdır. Tarihi bağlamıyla birlikte alışveriş yapmak yerine geleneksel Türk zanaatkârlığını yerinde gözlemleme fırsatı da sunar.",
    "Antalya Bit Pazarı": "Her hafta kurulan Antalya Bit Pazarı, antikacılardan el sanatlarına, eski müzik aletlerinden nadide kitaplara uzanan geniş ürün yelpazesiyle koleksiyoncuların ve meraklıların vazgeçilmez buluşma noktasıdır. Zaman zaman beklenmedik nostaljik nesnelerin keşfedilebildiği pazar, yerel halkın sosyalleşme mekânı olma özelliğini de koruyan canlı bir atmosfer taşır. Pazarın hemen yanındaki kahvehanelerde simit ve çay eşliğinde alışveriş deneyimi tamamlanabilir.",
    "Doğu Garaj Pazarı": "Her hafta Doğu Garaj Terminali çevresinde kurulan bu pazar, taze sebze ve meyveden tekstile, ev gereçlerinden elektronik aksesuarlara kadar geniş bir ürün yelpazesi sunar. Fiyatların AVM'lere kıyasla oldukça uygun olduğu pazar, Antalyalıların alışveriş ritmine katılmak isteyen gezginler için özgün bir yerel deneyim sunar. Sabah saatlerinde daha zengin ürün seçeneği bulunur; öğleden sonra standlar kapanmaya başlar.",
    "MarkAntalya AVM": "Şehir merkezinin hemen yakınında konumlanan MarkAntalya, Türkiye'nin önde gelen markalarının yanı sıra uluslararası zincirlerin de mağazalarını bir araya getiren büyük bir alışveriş merkezidir. Yemek katında yerel lezzetlerden fast food zincirlerine kadar pek çok seçenek bulunmaktadır. Sineması ve çocuk oyun alanıyla tüm gün geçirilebilecek kapsamlı bir alışveriş deneyimi sunar.",
    "TerraCity AVM": "Açık hava tasarımı ve geniş yeşil alanlarıyla TerraCity, Antalya'nın en modern alışveriş merkezlerinden biridir. Uluslararası lüks markaların mağazaları, geniş food court ve sinema kompleksi bulunmaktadır. Akşam saatlerinde terasta oturarak alışveriş sonrası dinlenmek için idealdir.",
    "Deepo AVM": "Outlet alışveriş konseptini benimseyen Deepo AVM, indirimli fiyatlarla marka ürünleri tercih edenler için Antalya'nın en cazip alışveriş noktalarından biridir. Çok sayıda Türk ve yabancı markanın stok kapatma ve sezon sonu ürünlerinin bir arada satıldığı geniş açık alan mağazalarıyla dikkat çeker. Geniş otoparkı ve merkeze yakın konumuyla ulaşımı son derece kolaydır.",
    "Kaleiçi Dükkanları": "Kaleiçi'nin taş döşeli sokaklarına sıralanan butik dükkânlar, turistlere Türk el sanatlarını ve yerel üretim ürünleri keşfetme fırsatı sunar. El boyaması seramikler, el işi deri çantalar, cam takılar ve özgün tasarım tekstil ürünleri bu dükkânların renkli vitrinlerini doldurur. Tarihi atmosfer içinde alışveriş yapmak, sıradan bir AVM deneyiminin çok ötesinde bir kültürel keşfe dönüşür.",
    "Migros Antalya": "Şehir içinde birden fazla şubesiyle hizmet veren Migros, günlük gıdadan ev ürünlerine kadar geniş bir ürün yelpazesi sunar. Türk peynirlerinden taze baharatlara, yerel zeytinyağından yöresel tatlılara kadar Antalya'ya özgü ürünleri bulmak için iyi bir adrestir. Uzun açık kalma saatleri ve pratik ödeme seçenekleriyle kolay bir alışveriş deneyimi sağlar.",
    "Antalya Resim ve Heykel Müzesi": "Cumhuriyet döneminden günümüze Türk resim ve heykel sanatının önemli eserlerini barındıran Antalya Resim ve Heykel Müzesi, Konyaaltı'nda sakin bir ortamda ziyaretçilerini bekler. Koleksiyonda hem Türk hem yabancı sanatçıların çalışmalarına yer verilmekte, yıl boyunca geçici sergiler düzenlenmektedir. Sanat ve kültüre ilgi duyanlar için şehrin diğer müzelerini tamamlayan keyifli bir duraktır.",
    "Kaleiçi Sanat Galerileri": "Kaleiçi'nin tarihi dokusu içine yerleşmiş küçük galeriler, yerel ve ulusal çağdaş sanatçıların çalışmalarını sergiler. Resim, heykel, fotoğraf ve seramikten oluşan koleksiyonlar zaman zaman satışa sunulmakta ve sanatçılarla birebir tanışma fırsatı yaratmaktadır. Tarihi konak ya da restore edilmiş kilise mekânlarında gerçekleşen galeri deneyimi, Kaleiçi gezisine sanatsal bir boyut ekler.",
    "7 Mehmet Restaurant": "1970'lerden bu yana hizmet veren 7 Mehmet, Antalya'nın en köklü ve ünlü restoranlarından biridir. Geniş bahçesinde sunulan menü, taze deniz ürünlerinden geleneksel Türk mezelere kadar uzanır; imza yemekleri arasında yöresel otlar ile pişirilen et yemekleri öne çıkar. Yerli müşterilerin ve yabancı konukların aynı masada buluştuğu bu mekânda yemek yemek, Antalya'ya özgü bir deneyimdir.",
    "Seraser Fine Dining": "Kaleiçi'nin restore edilmiş tarihi bir konağında kurulan Seraser, Antalya'nın en iddialı fine dining restoranlarından biridir. Türk mutfağının rafine yorumlarını Akdeniz malzemeleriyle harmanlayan şef ekibi, akşamları şarap eşliğinde romantik bir sofra deneyimi sunmaktadır. Taş avlulu bahçesi ve özenle tasarlanmış iç mekânıyla özel geceler için tercihlerin başında gelir.",
    "Vanilla Restaurant": "Konyaaltı sahilinin hemen üzerinde konumlanan Vanilla, modern Türk mutfağını uluslararası lezzetlerle birleştiren geniş menüsüyle akşam yemekleri için popüler bir seçenektir. Panoramik deniz ve dağ manzarasına karşı servis yapılan yemekler; zeytinyağlı mezeler, taze balık ve et seçenekleriyle zengin bir sofra sunar. Hafta sonları canlı müzik performansları mekânın atmosferini daha da zenginleştirir.",
    "Parlak Restaurant": "Parlak, Kaleiçi'nin merkezinde yıllardır aynı lezzetle hizmet veren geleneksel bir Türk restoranıdır. Pide, kebap ve yöresel güveç çeşitleri başta olmak üzere ev yapımı lezzetlere ev sahipliği yapar. Uygun fiyatları ve samimi atmosferiyle hem yerli hem yabancı ziyaretçiler tarafından sıklıkla tercih edilir.",
    "Yeşil Ev Kahvaltı": "Antalya'nın tarihi Kaleiçi semtinde, yeşil sarmaşıklı taş duvarlarla çevrili avlusunda hizmet veren Yeşil Ev Kahvaltı, geleneksel Türk sabah sofrası anlayışını yaşatmaktadır. Yöresel peynirler, zeytin çeşitleri, taze söğüş sebzeler ve ev yapımı reçellerle hazırlanan serpme kahvaltı sabahın erken saatinden öğlen ortasına kadar sunulmaktadır. Tarihi mekânın huzurlu atmosferinde vakit geçirmek, Antalya'ya has bir deneyim sunmaktadır.",
    "Club Arma": "Kaleiçi Limanı'nın hemen üzerindeki kayalık platformda kurulan Club Arma, gündüz beach club olarak işlev görürken akşam saatlerinde Antalya'nın en prestijli gece kulübüne dönüşür. Akdeniz'e bakan manzaralı terası, canlı DJ setleri ve profesyonel kokteyl barıyla hem yerel halkı hem tatilcileri ağırlar. Yaz gecelerinde rezervasyon yaptırmadan giriş bulmak oldukça güçleşmektedir.",
    "Dubliner Irish Pub": "Şehir merkezinde konumlanan Dubliner, Antalya'nın köklü yabancı publarından biridir. Soğuk bira çeşitleri, pub yemekleri ve özellikle büyük futbol maçları sırasında canlı atmosferiyle uluslararası bir kalabalığı bir araya getirir. Haftalık canlı müzik geceleri ve eğlenceli masa oyunları mekânı şehrin en sevilen sosyal buluşma noktalarından biri hâline getirmiştir.",
    "Konyaaltı Bar Sokağı": "Konyaaltı Sahil Parkı'nın iç kesiminde uzanan bu sokak, sırt sırta dizilmiş bar ve lounge mekânlarıyla Antalya'nın en canlı gece hayatı noktalarından birini oluşturmaktadır. Canlı müzikten DJ performanslarına, açık hava seanslarından spor yayınlarına kadar geniş bir eğlence yelpazesi sunar. Plaj deneyimini akşama kadar uzatmak isteyenler için yürüme mesafesindeki konum büyük avantaj sağlar.",
    "Rafting (Köprülü Kanyon)": "Köprülü Kanyon'un antik köprüler arasından geçen köpüklü akıntıları, Türkiye'nin en heyecanlı rafting güzergâhlarından biri olarak bilinmektedir. Deneyimli rehberlerin eşliğinde gerçekleştirilen tur; transfer, ekipman ve sigorta dahil sunulmakta ve yaklaşık 14 kilometre sürmektedir. Turun ardından kanyondaki alabalık restoranlarından birinde yemek yemek, macera gününe mükemmel bir son olur.",
    "Tekne Turu (Kaleiçi Marina)": "Kaleiçi Marinası'ndan kalkan tekne turları, günde birkaç sefer düzenlenerek yakınındaki mağaralara, Alt Düden Şelalesi'nin denize döküldüğü noktaya ve kristal berraklığındaki koylar uğrar. Turlar genellikle sabah başlayıp akşama kadar sürer; yüzme molaları, öğle yemeği ve güneşlenme imkânı sunulur. Denizden Antalya'nın tarihi sur ve kayalıklarını izlemek, karadan görülemeyen bir perspektif kazandırır.",
    "Tünektepe Teleferik": "Lara Platosu üzerinde 618 metre yüksekliğe çıkan Tünektepe Teleferik, Antalya'nın en panoramik bakış noktalarından birine ulaştırır. Tepede; şehir, sahil ve Torosların uzak silüeti tek bir karede bir araya gelir. Zirvedeki café-restoranda yenilen kahvaltı veya akşam yemeği, manzarayı daha da unutulmaz kılmaktadır.",
    "Zipline (Tünektepe)": "Tünektepe'deki zipline parkuru, yaklaşık 400 metre uzunluğundaki hattan adrenalin dolu bir uçuş deneyimi yaşatır. Teleferikle çıkılan zirvedeki aynı manzara, bu kez hareket hâlinde ve giderek alçalan bir açıyla izlenir. Güvenlik ekipmanları ve deneyimli eğitmenler eşliğinde gerçekleşen aktivite her yaş grubuna uygundur.",
    "Jeep Safari": "Torosların engebeli patikalarından Manavgat yakınlarındaki nehir kıyılarına uzanan Jeep Safari, Antalya'nın doğal güzelliklerini keşfetmenin en heyecanlı yollarından biridir. Off-road güzergâhlar boyunca şelale durakları, çoban köyleri ve orman manzaraları ziyaret edilir. Turlar genellikle sabah kalkan ve akşam dönen tam gün programı şeklinde düzenlenir; öğle yemeği serinletici bir nehir kıyısında servis edilir.",
    "Kesik Minare Camii": "Kaleiçi'nde Roma tapınağı olarak inşa edilen yapı sırasıyla Bizans kilisesi ve Osmanlı camiiine dönüştürülmüştür. 19. yüzyıldaki yangında yıkılan minaresinin yalnızca alt kısmı ayakta kaldığından yapı 'Kesik Minare' adını almıştır. Binlerce yıllık mimari katmanları bünyesinde barındıran bu tarihi yapı, zaman yolculuğu gibi bir deneyim sunmaktadır.",
    "Murat Paşa Camii": "Antalya'nın eski çarşı bölgesinde yer alan Murat Paşa Camii, 16. yüzyılda yapılmış olmasına karşın bugün hâlâ aktif bir ibadet mekânı olarak kullanılmaktadır. Beyaz badanalı dış cephesi, çini süslemeli mihrabı ve kurşun kaplı kubbeleriyle klasik Osmanlı camii mimarisinin sade güzelliğini yansıtır. Özellikle namaz vakitlerinde çevrenin oluşturduğu atmosfer ziyaretçileri derinden etkiler.",
    "Karatay Medresesi": "13. yüzyılda Anadolu Selçukluları tarafından inşa edilen Karatay Medresesi, Kaleiçi'nin ana caddesinde yer almaktadır. Portali üzerindeki ince Selçuklu taş işçiliği ve geometrik süslemeleri, döneminin ustaca mimarisini gözler önüne serer. Müzekart ile ücretsiz ziyaret edilebilen medrese, Anadolu'nun İslam öncesi ve sonrası kültürel mirasını harmanlayan nadide yapılar arasındadır.",
    "İskele Camii": "Kaleiçi'nin liman girişine hâkim konumuyla dikkat çeken İskele Camii, 16. yüzyılda Osmanlı döneminde inşa edilmiştir. Sade mimarisi ve limana bakan konumuyla şehrin tarihi dokusu içinde alçakgönüllü ama güçlü bir iz bırakmıştır. Özellikle denizin mavi rengiyle beyaz camii duvarlarının kontrast oluşturduğu sabah ışığında fotoğraf çekmek için ideal bir noktadır.",
    "Kalekap Hamamı": "Kaleiçi surlarının hemen içinde yer alan Kalekap Hamamı, Osmanlı döneminden günümüze aktarılan geleneksel Türk hamamı geleneğini yaşatmaktadır. Sıcak mermer göbektaşı ve kubbeli kemer tonozlardan süzülen loş ışıkla doğal bir atmosfere sahip olan hamam; kese, köpük masajı ve geleneksel bakım hizmetleri sunmaktadır. Tarihi çevre ve özgün mimariyle birleşince deneyim yalnızca bir bakımın çok ötesine geçer.",
    "Sefa Hamamı": "Kaleiçi'nin merkezinde tarihî bir yapıda hizmet veren Sefa Hamamı, geleneksel Türk hamamı ritüelini uygun fiyatlarla ve samimi bir atmosferde deneyimleme fırsatı sunar. Yerel halkın da düzenli olarak tercih ettiği bu hamam, turistik yoğunluğun ötesinde özgün bir kültür deneyimi sunmaktadır. Sabah seansları hem daha sakin hem de daha taze bir deneyim için önerilmektedir.",
    "Antalya Spa & Wellness": "Antalya'nın premium otel bölgelerinde konumlanan Antalya Spa & Wellness, hammam, sauna, çamur banyosu ve aromaterapi masajı gibi kapsamlı hizmetleri tek çatı altında sunar. Akdeniz bitkileri ve doğal minerallerin esas alındığı bakım protokolleri, enerji yenileme ve derin gevşeme sağlamak üzere tasarlanmıştır. Plaj ve tarihi tur yorgunluğunu atmak isteyen konuklar için idealdir.",
}

conn = sqlite3.connect('c:/Users/bilge/travelmind/backend/travelmind.db')
cur = conn.cursor()

updated = 0
for name, desc in DESCRIPTIONS.items():
    cur.execute("UPDATE activities SET description=? WHERE name=?", (desc, name))
    if cur.rowcount > 0:
        updated += 1

conn.commit()
conn.close()
print(f"Updated {updated} / {len(DESCRIPTIONS)} activities")
